<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="Ecommerce.tests.DataDrivenCheckTest">
        <methods>
          <include name="orderHistoryTest"/>
          <include name="submitOrder" invocation-numbers="0 2"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- Ecommerce.tests.DataDrivenCheckTest -->
      <class name="Ecommerce.tests.ErrorValidationTest">
        <methods>
          <include name="ProductErrorValidation" invocation-numbers="0 2"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- Ecommerce.tests.ErrorValidationTest -->
      <class name="Ecommerce.tests.StandAloneTestRefractedTest">
        <methods>
          <include name="submitOrder"/>
          <include name="orderHistoryTest"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- Ecommerce.tests.StandAloneTestRefractedTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
